# Generated by Django 6.0.6 on 2026-06-09 10:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Muž'), ('female', 'Žena')], max_length=6)),
                ('start_date', models.DateField()),
                ('birth_date', models.DateField()),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Muž'), ('female', 'Žena')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='origin',
            field=models.CharField(blank=True, max_length=100, verbose_name='Odkud je'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reliable',
            field=models.BooleanField(default=False, verbose_name='Spolehlivý'),
        ),
        migrations.AddField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='appka.employee'),
        ),
    ]
