# Generated by Django 6.0.4 on 2026-06-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appka', '0003_alter_customer_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='customers/'),
        ),
    ]
